format = """
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$golang\
$nodejs\
$python\
[](fg:#86BBD8 bg:#06969A)\
$aws\
$kubernetes\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[aws]
symbol = "󰸏"
style = "bg:#06969A fg:#000000"
format = '[ $symbol $region ]($style)'
force_display = true

[character]
format = ' $symbol '
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vicmd_symbol = '[❮](bold green)'
disabled = false

[directory]
style = "bg:#DA627D fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol="󱃾"
style="bg:#06969A fg:#000000"
format='[ $symbol $context( \($namespace\)) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#86BBD8 fg:#000000"
format = '[ $symbol ($version) ($virtualenv) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'
